apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubesecure-api-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aadieng100/KubeSecure-GitOps.git'
    targetRevision: HEAD
    path: helm/kubesecure-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubesecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
